name: Deployment pipeline

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      # - name: Install project dependencies
      #   working-directory: ./part11
      #   run: npm install
      - name: Lint style
        working-directory: ./part11
        run: npm run eslint

      - name: Run tests
        working-directory: ./part11
        run: npm test
        
      - name: Make script executable
        working-directory: ./part11
        run: chmod +x build_step.sh

      # - name: Create Build
      #   working-directory: ./part11
      #   run: npm run build
      - name: Execute build script
        working-directory: ./part11
        run: ./build_step.sh

      - name: Install playwright browsers
        working-directory: ./part11
        run: npx playwright install --with-deps

      - name: Run playwright tests
        working-directory: ./part11
        run: npm run test:e2e
