name: Deployment pipeline

on: 
  push:
    branches:
      - main

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install project dependencies
        working-directory: ./part11
        run: npm install

      - name: Lint style
        working-directory: ./part11
        run: npm run eslint

      - name: Run tests
        working-directory: ./part11
        run: npm test

      - name: Create Build
        working-directory: ./part11
        run: npm run build
